env:
  global:
  - secure: A2lzVc/W3ByK3b1lHx5/xTfB2MdRJOt1nvzn91Y5TFgslv/4vJNywIYHgOcDObWL6fSTgL0/P0/CY3mg1Dp0gMqHbexr2ZQFNzaxnfZAqkoyfUWKTettnRS7CAQGZwn9QmklCd2CTIt4BSwSFcmParrJ1p2L8YJhnmDWWr8hHnG80es6HiPeU1Ds61g/lIwGbydUUbwEZc+avpEBf8dqZZn7no9WNTQIx9fMSackFLG75Spfrpm/GXwcPNZWVpFOacHgJS1vdIL3zU4uWdfG+YV6Ph6uSeY7/vjCN5CZpztetRfAuu2EHcxm05ZpF3V8TRLMJxhOpX+8obQ+uusXt7f4xsqNlpJK/57sysW9lYw/uxgnZbb8KmqREjgrr6cF5H6rf7aIgVUo3poeg1pYRCN+GhLVFWU1TAt0WX0v92dgM1PjfmKoz4ShDEt80vLimML/zLYqVVhwiG8AXqkSw24HxX7xYBGIEZtWA3QsFoDOze0Ng0C/uE56XcPmfkYrywi9Ep1lLrqd6eOvovArsnzyrVaPW8dFfzmiVNlspmvS/turx7S5hHkMrP552q2qzWL0J8AZKsm5BP+7HDK5hM8cP8trBPoFBzWmp0EV7lyjpSezck9SZny3BZBWjsmcwKOAAYrJipQDDqFwJ6pFVTT7bl9msJvp6lVBxAEYApo=
  - secure: UUrTAZpuVy2T5dOLMAeWv3iTuol9wXSpJuc3Sr5E1ookzlDoq8pHMStDY0lecna84xKvmfeV/z6etW6+olIjUR+EtpXs2d9XZW1tQFDQv6XfX7LYcy+y0LfdxOdIKG2zw3iRASiPXQTJJ0Bn8GSiqkwNhN6Eso6Bj7goXz1ndnZgPx1ezmuVeVY4UaO1ml7s4cZl6fFymSzEEnAsIrqm8kD+1BCQXLMpwtEWt8KBtWQAEZKhJQJpjEUJxP+T2aLDiK5ifDjghUxnB/jiJ94xM0Cbe/S9yzYS/3Pul7O1fd9iZD10czA/V2vYLCU6FllGwHkC6EyrMnt+Tm5yFp4voWBucF/0aTmqFFIrV4mL1g8sqkwn89sKqxE8TA6O0i690vAaT6LWKZCPXOko7pVaeR/hjbTC3PIcthsj5g5mKGm1E99USfg9ilZVoy9C/etiPyhrbNMkszXguHy3a254iz3Km6ZMGCMhkCsAc7jCFOIiVv2BHqR7xS0bDzSCLZEILKiehSNIVNnWJKV6z/WEudTNQR6ebjxHCSXJsf3meXpKXedafYxFjdnDVdW3dFXejJZ8//XieL3uuwjvTZ8A1uQ2Xgw5qd/zEDEfcBXhHNZbEJ0dzK79o5x7bNjeuvEFSSO1DCE96ed239nawhZhlRSAzjsE1XjoTNJawknRUdg=

language: objective-c
osx_image: xcode8.3

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  - bundler

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - set -o pipefail
  - bundle exec danger
